export default {
  greeting: "Лучшая мебель для вашего замка...",
  welcome: "Новая коллекция мебелиТенденции 2020 года",
  changeLanguage:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscinginphasellus не в порядке.",
  btn: "Купить сейчас",
  Featured: "Рекомендуемые продукты",
  Leatest: "Самые некачественные продукты",
  link1: "Новое поступление",
  link2: "Бестселлер",
  link3: "Рекомендуемые",
  link4: "Специальное предложение",
  whot1: "Что предлагает Shopex!",
  whot2: "24/7 поддержка",
  whot3:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Массапурус беременных.",
  kata1: "Уникальные особенности новейших и трендовых продуктов",
  kata2: "Все рамы изготовлены из массива твердой древесины и ламината",
  kata3:
    "Укреплен двойными деревянными штифтами, клеем, шурупами - гвоздями, угловыми блоками и блоками с машинными гвоздями и машинными гвоздями.",
  kata4: "Подлокотники, спинки и сиденья структурно усилены",
  kata5: "Добавить на карту",
  kata6: "B&B итальянский диван",
  treding1: "Трендовые продукты",
  treding2: "Товар со скидкой",
  link5: "Деревянный стул",
  link6: "Пластиковый стул",
  link7: "Коллекция диванов",
  top1: "Лучшие категории",
  get1: " Получайте последние обновления, подписавшись на нашу рассылку",
  get2: "Последний блог",
  // FAQ
  faq1: "Часто задаваемые вопросы",
  faq2: "Общая информация",
  faq3: "Eu dictumst cum at sed euismood condimentum?",
  faq4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tincidunt sed tristique mollis vitae, consequat gradida sagittis.",
  faq5: "«Magna bibendum estfermentum eros.",
  faq6: "Odio muskana hak eris conseekin sceleton?",
  faq7: "Элит ид бландит сабара бои велик гуа мара?",
  faq8: "Ask a Question",
  faq9: "Отправить почту",
  //  about
  about1: "Сетка магазина по умолчанию",
  about2: "Узнайте о нашем бизнесе электронной коммерции, истории",
  about3:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mattis neque ultrices mattis aliquam, Malesuada Diam Est. Malesuada sem tristique Amet Erat vitae Eget Dolor Lobortis. Accumsan faucibus vitae lobortis quis bibendum quam.",
  about4: "Связаться с нами",
  about5: "Наши возможности",
  about6: "Бесплатная доставка",
  about7: "100% кэшбэк",
  about8: "Качественный продукт",
  about9: "Круглосуточная поддержка",
  about10:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Massapurus gravida.",
  about111: "Наш клиент говорит!",
  about11: "Селена Гомес",
  about12: "Генеральный директор Webecy Digital",
  about13:
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Non duis ultrices quam vel dui sollicitudin aliquet id arcu. Nam vitae a enim nunc, sed sapien egestas ac nam. Tristique ultrices dolor aliquam lacus volutpat praesent.",
  shop1: "Скидка 23% на все товары",
  shop2: "Уютный диван",
  shop3: "Элегантный стол",
  shop4: "Красивые лампы",
  shop5: "Стильный шкаф",
  shop6: "Декоративные подушки",
  shop7: "Удобное кресло для офиса",
  shop8: "Кофейный столик",
  shop9: "Современная мебель для ванной",
  shop10: "Шкаф с зеркалом",
  shop11: "Роскошный пуф",
  shop12: "Язик"  
};
