export default {
  greeting: "Qal'angiz uchun eng yaxshi mebel....",
  welcome: "Yangi mebel kolleksiyasi 2020 yilgi trendlar",
  changeLanguage:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscingin phasellus in justo.",
  btn: "Hozir xarid qiling",
  Featured: "Tanlangan mahsulotlar",
  Leatest: "Eng so'nggi mahsulotlar",
  link1: "Yangi kelgan",
  link2: "Bozori chaqqon",
  link3: "Tavsiya etilgan",
  link4: "Maxsus taklif",
  whot1: "Shopex qanday taklif qiladi!",
  whot2: "24/7 yordam",
  whot3:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Massayiringli tortish.",
  kata1: "Eng so'nggi va ommabop mahsulotlarning o'ziga xos xususiyatlari",
  kata2: "Barcha ramkalar qattiq yog'och va laminat bilan qurilgan",
  kata3:
    "Ikkita yog'och dübeller, elim, vint - mixlar burchak bloklari va mashina mixlari bloklari va mashina mixlari bilan mustahkamlangan",
  kata4: "Qo'llar, orqa va o'rindiqlar tizimli ravishda mustahkamlangan",
  kata5: "Cardga qo'shish",
  kata6: "B&B italyancha divan",
  treding1: "Trenddagi mahsulotlar",
  treding2: "Chegirmali element",
  link5: "Yog'och stul",
  link6: "Plastik stul",
  link7: "Divanlar kolleksiyasi",
  top1: "Eng yaxshi toifalar",
  get1: "Yangiliklarga obuna bo'lish orqali eng so'nggi yangiliklarni oling",
  get2: "Eng so'nggi blog",
  // FAQ
  faq1: "TSS",
  faq2: "Umumiy ma'lumot",
  faq3: "Eu dictumst cum va sed euismmood condimentum?",
  faq4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tincidunt sed tristique mollis vitae, natijada gravida sagittis.",
  faq5: "Magna bibendum est fermentum eros.",
  faq6: "Odio muskana hak eris conseekin sceleton?",
  faq7: "Elit id blandit sabara boi velit gua mara?",
  faq8: "Savol bering",
  faq9: "Pochta yuborish",
  // about
  about1: "Birlamchi xaridlar tarmog‘i",
  about2: "Bizning elektron tijorat biznesimiz, tariximiz haqida biling",
  about3:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mattis neque ultrices mattis aliquam, malesuada diam est.Malesuada sem tristique amet erat vitae eget dolor lobortis. Accumsan faucibus vitae lobortis quis bibendum quam.",
  about4: "Biz bilan bog'lanish",
  about5: "Bizning xususiyatlarimiz",
  about6: "Bepul yetkazib berish",
  about7: "100% naqd pulni qaytarish",
  about8: "Sifatli mahsulot",
  about9: "24/7 qo'llab-quvvatlash",
  about10:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Massapurus gravida.",
  about111: "Bizning mijozimiz aytadi!",
  about11: "Selena Gomez",
  about12: "Webecy Digital kompaniyasining bosh direktori",
  about13:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Non duis ultrices quam vel dui sollicitudin aliquet id arcu. Nam vitae a enim nunc, sed sapien egestas ac nam. Tristique ultrices dolor aliquam lacus volutpat praesent.",
  shop1: "Barcha mahsulotlarga 23% chegirma",
  shop2: "Yumshoq divan",
  shop3: "Zamonaviy stol",
  shop4: "Chiroyli chiroqlar",
  shop5: "Stilistik shkaf",
  shop6: "Dekorativ yostiqlar",
  shop7: "Ofis uchun qulay kreslo",
  shop8: "Kofe stoli",
  shop9: "Zamonaviy vannaxonadagi mebel",
  shop10: "Kuzatish uchun shkaf",
  shop11: "Hashamatli puf",
  shop12: "Til",
};
