export default {
  greeting: "Best Furniture For Your Castle....",
  welcome: "New Furniture CollectionTrends in 2020",
  changeLanguage:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscingin phasellus non in justo.",
  btn: "Shop Now",
  Featured: "Featured Products",
  Leatest: "Leatest Products",
  link1: "New Arrival",
  link2: "Best Seller",
  link3: "Featured",
  link4: "Special Offer",
  whot1: "What Shopex Offer!",
  whot2: "24/7 Support",
  whot3:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Massapurus gravida.",
  kata1: "Unique Features Of leatest & Trending Poducts",
  kata2: "All frames constructed with hardwood solids and laminates",
  kata3:
    "Reinforced with double wood dowels, glue, screw - nails cornerblocks and machine nails blocks and machine nails",
  kata4: "Arms, backs and seats are structurally reinforced",
  kata5: "Add To Cart",
  kata6: "B&B Italian Sofa ",
  treding1: "Trending Products",
  treding2: "Discount Item",
  link5: "Wood Chair",
  link6: "Plastic Chair",
  link7: "Sofa Colletion",
  top1: "Top Categories",
  get1: " Get Leatest Update By Subscribe 0ur Newslater",
  get2: "Leatest Blog",
  // FAQ
  faq1: "Faq",
  faq2: "General Information",
  faq3: "Eu dictumst cum at sed euismood condimentum?",
  faq4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tincidunt sed tristique mollis vitae, consequat gravida sagittis.",
  faq5: "Magna bibendum est fermentum eros.",
  faq6: "Odio muskana hak eris conseekin sceleton?",
  faq7: "Elit id blandit sabara boi velit gua mara?",
  faq8: "Ask a Question",
  faq9: "Send Mail",
  // about
  about1: "Shop Grid Default",
  about2: "Know About Our Ecomerce Business, History",
  about3:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mattis neque ultrices mattis aliquam, malesuada diam est. Malesuada sem tristique amet erat vitae eget dolor lobortis. Accumsan faucibus vitae lobortis quis bibendum quam.",
  about4: "Contact us",
  about5: "Our Features",
  about6: "Free Delivery",
  about7: "100% Cash Back",
  about8: "Quality Product",
  about9: "24/7 Support",
  about10:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Massapurus gravida.",
  about111: "Our Client Say!",
  about11: "Selina Gomez",
  about12: "Ceo At Webecy Digital",
  about13:
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Non duis ultrices quam vel dui sollicitudin aliquet id arcu. Nam vitae a enim nunc, sed sapien egestas ac nam. Tristique ultrices dolor aliquam lacus volutpat praesent.",
  shop1: "23% off in all products",
  shop2: "Cozy Sofa",
  shop3: "Elegant Table",
  shop4: "Beautiful Lamps",
  shop5: "Stylish Cabinet",
  shop6: "Decorative Cushions",
  shop7: "Comfortable Office Chair",
  shop8: "Coffee Table",
  shop9: "Modern Bathroom Furniture",
  shop10: "Mirror Cabinet",
  shop11: "Luxurious Pouf",
  shop12: "Language"

};