export default {
  greeting: "Best Furniture For Your Castle....",
  welcome: "New Furniture CollectionTrends in 2020",
  changeLanguage:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscingin phasellus non in justo.",
  btn: "Shopping",
  Featured: "Featured Products",
  Leatest: "Leatest Products",
  link1: "New Arrival",
  link2: "Best Seller",
  link3: "Featured",
  link4: "Special Offer",
  whot1: "What Shopex Offer!",
  whot2: "24/7 Support",
  whot3:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Massapurus gravida.",
  kata1: "Unique Features Of leatest & Trending Poducts",
  kata2: "All frames constructed with hardwood solids and laminates",
  kata3:
    "Reinforced with double wood dowels, glue, screw - nails cornerblocks and machine nails blocks and machine nails",
  kata4: "Arms, backs and seats are structurally reinforced",
  kata5: "Shopping",
  kata6: "B&B Italian Sofa ",
  treding1: "Trending Products",
  treding2: "Discount Item",
  link5: "Wood Chair",
  link6: "Plastic Chair",
  link7: "Sofa Colletion",
  top1: "Top Categories",
  get1: " Get Leatest Update By Subscribe 0ur Newslater",
  get2: "Leatest Blog",
  // FAQ
  faq1: "Faq",
  faq2: "General Information",
  faq3: "Eu dictumst cum at sed euismood condimentum?",
  faq4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tincidunt sed tristique mollis vitae, consequat gravida sagittis.",
  faq5: "Magna bibendum est fermentum eros.",
  faq6: "Odio muskana hak eris conseekin sceleton?",
  faq7: "Elit id blandit sabara boi velit gua mara?",
  faq8: "Ask a Question",
  faq9: "Send Mail",
  // about
  about1: "Shop Grid Default",
  about2: "Know About Our Ecomerce Business, History",
  about3:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mattis neque ultrices mattis aliquam, malesuada diam est. Malesuada sem tristique amet erat vitae eget dolor lobortis. Accumsan faucibus vitae lobortis quis bibendum quam.",
  about4: "Contact us",
  about5: "Our Features",
  about6: "Free Delivery",
  about7: "100% Cash Back",
  about8: "Quality Product",
  about9: "24/7 Support",
  about10:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Massapurus gravida.",
  about111: "Our Client Say!",
  about11: "Selina Gomez",
  about12: "Ceo At Webecy Digital",
  about13:
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Non duis ultrices quam vel dui sollicitudin aliquet id arcu. Nam vitae a enim nunc, sed sapien egestas ac nam. Tristique ultrices dolor aliquam lacus volutpat praesent.",
  shop1: "23% off in all products",
  shop2: "Cozy Sofa",
  shop3: "Elegant Table",
  shop4: "Beautiful Lamps",
  shop5: "Stylish Cabinet",
  shop6: "Decorative Cushions",
  shop7: "Comfortable Office Chair",
  shop8: "Coffee Table",
  shop9: "Modern Bathroom Furniture",
  shop10: "Mirror Cabinet",
  shop11: "Luxurious Pouf",
  shop12: "Language",
  info1: "Description",
  info2: "Additional Info",
  info3: "Reviews",
  info4: "Video",
  info5: "Varius tempor.",
  info6: "Aliquam dis vulputate vulputate integer sagittis. Faucibus dolor ornare faucibus vel sed et eleifend habitasse amet. Montes, mauris varius ac est bibendum. Scelerisque a, risus ac ante. Velit consectetur neque, elit, aliquet. Non varius proin sed urna, egestas consequat laoreet diam tincidunt. Magna eget faucibus cras justo, tortor sed donec tempus. Imperdiet consequat, quis diam arcu, nulla lobortis justo netus dis. Eu in fringilla vulputate nunc nec. Dui, massa viverr .",
  info7: "More details",
  info8: "Aliquam dis vulputate vulputate integer sagittis. Faucibus ds diam arcu, nulla lobortis justo netus dis. Eu in fringilla vulputate nunc nec. Dui, massa viverr .",
  order1: "Order Completed",
  order2: "Your Order Is Completed! ",
  order3: "Thank you for your order! Your order is being processed and will be completed within 3-6hours. You will receive an email confirmation when your order is completed.",
  order4: "Continue Shopping",
  wishlist1: "No favorite products yet",
  nav1: "Home",
  nav2: "About",
  nav3: "Faq",
  nav4: "Blog",
  nav5: "Shop",
  nav6: "Contact",
  nav7: "Hekto",
};